feat(UIKIT-737): Реализован mobilePhone, добавлено описание в Readme.md
kaluga-astral/validations pull request #37
Opened 2023-05-18 13:32 UTC by agro196

2023-05-18 13:38 UTC, AndTem requested changes

2023-05-18 13:38 UTC, AndTem commented on package/src/mobilePhone/mobilePhone.ts
> + * @description Проверяет валиден ли мобильный телефон
Напиши, что валидный телефон начинается с 79 и не содержит символов, кроме цифр

2023-05-18 13:38 UTC, AndTem commented on package/src/mobilePhone/mobilePhone.ts
> +      const createMobilePhoneError = () =>
Ненужная функция. Просто верни ошибку

2023-05-18 13:38 UTC, AndTem commented on README.md
> +Проверяет валиден ли мобильный телефон
Надо добавить информацию, что телефон должен начинаться на 79

2023-05-18 13:38 UTC, AndTem commented on README.md
> +### innIP
innUL забыл

2023-05-18 13:38 UTC, AndTem commented on README.md
> +### snils
Надо добавить новые разделы в Table of contents

2023-05-19 05:14 UTC, AndTem approved these changes

2023-05-19 06:29 UTC, YrStudenikin approved these changes

2023-05-19 06:35 UTC, merged