Validations surname
kaluga-astral/validations pull request #56
Opened 2023-07-11 11:58 UTC by Endermanch

# Чеклист

- [x] Написать тесты
- [x] Описать jsdoc
- [x] Обновить документацию в README.md

2023-07-11 12:05 UTC, olewka40 approved these changes

2023-07-12 03:41 UTC, Ofigelov requested changes

2023-07-12 03:41 UTC, Ofigelov commented on package/src/surname/surname.ts
> +      if (!/^[А-ЯЁIV'][а-яёА-ЯЁIV' .,()-]*[а-яё]$/.test(value)) {
Давай вынесем регулярки в отдельные константы.

2023-07-12 03:41 UTC, Ofigelov commented on package/src/surname/surname.ts
> +        return createSurnameError();
Правила валидации для фамилии по минтруду - довольно сложные, и пользователю будет проблемно понять, где же он ошибся, если мы будем ему просто каждый раз говорить "Некорректная фамилия". Давай на каждую ошибку, будем подсказывать что именно не так, если неверная длинна "Фамилия не может быть длиннее 20 символов", если повторяются спецсимволы, то отвечаем "Фамилия не может содержать повторяющиеся спецсимволы". И т.д.

2023-07-14 04:14 UTC, Ofigelov commented on package/src/surname/constants.ts
> +    'Фамилия может содержать только буквы русского алфавита, буквы I, V латинского алфавита и следующие спецсимволы: -;  ; .; \'; ,; (; );',
eslint не пропускает изменения, если в строке встречается экранирование одинарной кавычки, то тогда надо 
всю строку заворачивать в двойные, вместо одинарных.

в файле с тестами тоже есть такие строки

2023-08-03 09:18 UTC, closed without merging