feat(UIKIT-784): Реализовал правила валидации для ФИО
kaluga-astral/validations pull request #58
Opened 2023-07-31 07:48 UTC by IgorBabikov

# Чеклист

- [ ] Написать тесты
- [ ] Описать jsdoc
- [ ] Обновить документацию в README.md

2023-08-01 07:18 UTC, AndTem requested changes

2023-08-01 07:18 UTC, AndTem commented on package/src/name/constants.ts
> +export const RESTRICTED_VALUES = [];
лишняя константа

2023-08-01 07:18 UTC, AndTem commented on package/src/name/name.ts
> +      return;
```suggestion
      return undefined;
```

2023-08-01 07:18 UTC, AndTem commented on package/src/name/name.test.ts
> +  it('Должна возвращать ошибку, если имя не начинается или не заканчивается буквой', () => {
Есть обрабатка первой части кейса, но нет проверки для второй части

2023-08-01 07:18 UTC, AndTem commented on package/src/name/name.test.ts
> +  it('Должна возвращать ошибку, если имя содержит два или более подряд идущих спецсимволов или пробелы', () => {
Для большинства описанных кейсов необходимо использовать it.each и проверять как можно больше недопустипым символов и кейсов. Смотри как сделано в других правилах

2023-08-01 07:18 UTC, AndTem commented on package/src/patronymic/patronymic.ts
> +      if (!/^[а-яёА-ЯЁIV][а-яёА-ЯЁIV'-.,() ]*[а-яёА-ЯЁIV]$/.test(value)) {
повторяющийся функционал между правилами. Надо переиспользовать

2023-08-01 07:18 UTC, AndTem commented on package/src/patronymic/patronymic.ts
> +      if (/[' .,()-]{2}/.test(value)) {
повторяющийся функционал между правилами. Надо переиспользовать

2023-08-01 07:18 UTC, AndTem commented on package/src/name/name.ts
> +      if (!/^[а-яёА-ЯЁIV'-.,() ]+$/.test(value)) {
повторяющийся функционал между правилами. Надо переиспользовать

2023-08-01 07:19 UTC, AndTem requested changes

2023-08-01 07:19 UTC, AndTem commented on README.md
> +Проверяет валидна ли имя
```suggestion
Проверяет валидно ли имя
```

2023-08-01 07:19 UTC, AndTem commented on README.md
> +### name
Не добавил приавла в table of content

2023-08-01 07:21 UTC, AndTem commented
Переименуй название PR: Реализовал -> Реализованы.

Заголовок PR попадет в changelog

2023-08-01 07:24 UTC, Ofigelov commented
Обратите внимание, изменения пересекаются с https://github.com/kaluga-astral/validations/pull/56/files

2023-08-01 09:48 UTC, IgorBabikov commented on package/src/name/name.test.ts
> +  it('Должна возвращать ошибку, если имя не начинается или не заканчивается буквой', () => {
В регулярке - 
      if (!/^[а-яёА-ЯЁIV][а-яёА-ЯЁIV'-.,() ]*[а-яёА-ЯЁIV]$/.test(value)) {
        return createNameError();
      }

2023-08-01 09:52 UTC, AndTem commented on package/src/name/name.test.ts
> +  it('Должна возвращать ошибку, если имя не начинается или не заканчивается буквой', () => {
Так надо же доказать, что при обоих кейсах будет ошибка

2023-08-01 12:19 UTC, IgorBabikov commented on package/src/patronymic/patronymic.ts
> +      if (!/^[а-яёА-ЯЁIV][а-яёА-ЯЁIV'-.,() ]*[а-яёА-ЯЁIV]$/.test(value)) {
Может мне создать 1 папку, к примеру - "fullName" ? в ней уже будут лежать папки: name, surname, patronymic и в fullName еще создам utils, в нее уже помещу те регулярки, которые используются часто.

2023-08-02 07:15 UTC, IgorBabikov commented on package/src/patronymic/patronymic.ts
> +      if (/[' .,()-]{2}/.test(value)) {
Вынес в utils регулярные выражения, которые используется в разных местах

2023-08-02 08:54 UTC, AndTem requested changes

2023-08-02 08:54 UTC, AndTem commented on package/src/core/utils/isCheckValidLength/isCheckValidLength.ts
> +export const isCheckValidLength = (value: string): boolean =>
Название этой утилы никак не соотносится с тем, для она предназначена

2023-08-02 08:54 UTC, AndTem commented on package/src/core/utils/isCheckForSpecialCharacters/isCheckForSpecialCharacters.ts
> +export const isCheckForSpecialCharacters = (value: string): boolean =>
Название этой утилы никак не соотносится с тем, для она предназначена

2023-08-02 08:54 UTC, AndTem commented on package/src/core/utils/isCheckForSpecialCharacters/isCheckForSpecialCharacters.ts
> +export const isCheckForSpecialCharacters = (value: string): boolean =>
Есил выносишь утилы, то для них должны быть написаны тесты

2023-08-02 08:54 UTC, AndTem commented on package/src/name/index.ts
> +export * from './name';
Нужны экспорты из индексного файла пакета

2023-08-02 08:54 UTC, AndTem commented on package/src/core/utils/isCheckValidLength/isCheckValidLength.ts
> +export const isCheckValidLength = (value: string): boolean =>
Тут скорее что-то вроде: fullNameLength

2023-08-02 08:54 UTC, AndTem commented on package/src/patronymic/patronymic.test.ts
> +    '',
Нет проверки на длинну

2023-08-02 08:54 UTC, AndTem commented on package/src/patronymic/patronymic.test.ts
> +    'Иванович.Иванович',
Не вижу кейсов с I и V.
Проверь все кейсы по требованиям

2023-08-02 10:54 UTC, IgorBabikov commented on package/src/patronymic/patronymic.test.ts
> +    '',
@AndTem благодаря  '' проверяется что в строке есть символы. Если указать проверку для > 200 в it.each стоит добавить все 200 букв ? к примеру:
 it.each<string>([
    '' - проверяем, что в строке что-то есть
    '**.......**тут указать 200 любых букв?'  -  проверяем, что не содержит больше 200

2023-08-03 09:13 UTC, AndTem requested changes

2023-08-03 09:13 UTC, AndTem commented on package/src/core/utils/hasConsecutiveChars/hasConsecutiveChars.test.ts
> +  ])('Возвращает "%s" со значением %s', (value, expected) => {
Описание кейса вообще не соответсвует тому, что проверяется

2023-08-03 09:13 UTC, AndTem commented on package/src/core/utils/hasConsecutiveChars/hasConsecutiveChars.test.ts
> +  ])('Возвращает "%s" со значением %s', (value, expected) => {
И each в данном случае бесполезен

2023-08-03 09:13 UTC, AndTem commented on package/src/core/utils/fullNameLength/fullNameLength.ts
> + * @description Проверяет, что длина текста минимум 1 символ, максимум 200
description надо поправить

2023-08-03 09:13 UTC, AndTem commented on package/src/core/utils/fullNameLength/fullNameLength.test.ts
> +  it.each([
Сделай два отдельный each на разные результаты

2023-08-03 09:13 UTC, AndTem commented on package/src/core/utils/isCheckValidCharacters/isCheckValidCharacters.test.ts
> +    ['123', true],
На разные результаты должны быть свои each

2023-08-03 09:13 UTC, AndTem commented on package/src/core/utils/isCheckValidCharacters/isCheckValidCharacters.ts
> +export const isCheckValidCharacters = (value: string): boolean =>
Ты в core поместил функцию с названием isCheckValidCharacters. Значит эта утила проверяет валидные символы прямо для всех правил?

2023-08-03 09:13 UTC, AndTem commented on package/src/name/name.ts
> +      // прописные (большие) буквы I и V латинского алфавита, -, пробел, точка, апостроф, запятая, открывающая и закрывающая скобка
этот текст у тебя написан внутри утилы, дублировать его не имеет смысла

2023-08-03 09:13 UTC, AndTem commented on package/src/name/name.test.ts
> +  ])('Valid for: %s', (value) => {
up

2023-08-03 09:13 UTC, AndTem commented on README.md
> +// Примеры значений из списка требований
Почему ты ссылку вставил в блок с кодом, а не в md?
И там примеров нет, там требования

2023-08-03 10:29 UTC, IgorBabikov commented on package/src/core/utils/isCheckValidCharacters/isCheckValidCharacters.ts
> +export const isCheckValidCharacters = (value: string): boolean =>
В данном регулярном выражении указаны все символы, которые считаются допустимыми для всех правил.

2023-08-03 14:48 UTC, AndTem commented on package/src/core/utils/hasConsecutiveChars/hasConsecutiveChars.test.ts
> +  ])('Возвращает "%s" со значением %s', (value, expected) => {
В других тестах такая же ситуация

2023-08-03 14:58 UTC, AndTem commented on package/src/surname/surname.test.ts
> +      'Valid for: Иванов-Иванов. Допускается дефис между буквами',
😊️️️️️️
Each используется для применения набора данных к одному кейсы. Ты же запихнул несколько кейсов в один each, чем усложнил тесты и надублировал код.
Я уже писал в комменте как это должно выглядеть

2023-08-03 15:02 UTC, AndTem requested changes

2023-08-03 15:02 UTC, AndTem commented on README.md
> +### [Требования на реализацию](https://track.astral.ru/soft/wiki/pages/viewpage.action?pageId=3813152849#id-Требованиянареализацию-Требование5.Поле"Имя")
```suggestion
#### [Требования на реализацию](https://track.astral.ru/soft/wiki/pages/viewpage.action?pageId=3813152849#id-Требованиянареализацию-Требование5.Поле"Имя")
```

2023-08-03 15:10 UTC, IgorBabikov commented on package/src/name/name.test.ts
> +  ])('Valid for: %s', (value) => {
![image](https://github.com/kaluga-astral/validations/assets/72324970/66958890-de27-44f8-8408-c76c20478805)

Я же изменил везде на такой подход.

2023-08-07 08:40 UTC, AndTem requested changes

2023-08-07 08:40 UTC, AndTem commented on package/src/name/name.test.ts
> +  it.each(['Генрих-v', 'Генрих-i', 'v-Генрих', 'i-Генрих'])(
дубликат

2023-08-07 08:40 UTC, AndTem commented on package/src/core/utils/fullNameLength/fullNameLength.ts
> +export const fullNameLength = (value: string): boolean =>
```suggestion
export const isFullNameLength = (value: string): boolean =>
```

2023-08-07 08:43 UTC, AndTem commented
Сделай, пожалуйста, для правил name, surname, patronymic префикс person:
personName...

2023-08-07 09:56 UTC, IgorBabikov commented on package/src/name/name.test.ts
> +  it.each(['Генрих-v', 'Генрих-i', 'v-Генрих', 'i-Генрих'])(
Тут проверка на маленькие i и v. У меня есть проверки как на большие I, V:
  "Генрих-V', 'Генрих-I', 'V-Генрих', 'I-Генрих"
так и на маленькие i и v:
 "Генрих-v', 'Генрих-i', 'v-Генрих', 'i-Генрих".

Или ты имеешь ввиду что Генрих повторяется в разных файлах ?

2023-08-07 10:35 UTC, AndTem commented on package/src/name/name.test.ts
> +  it.each(['Генрих-v', 'Генрих-i', 'v-Генрих', 'i-Генрих'])(
Понял, ок

2023-08-07 11:19 UTC, AndTem approved these changes

2023-08-07 11:35 UTC, perevezencev approved these changes

2023-08-07 11:56 UTC, merged