feat(UIKIT-785): Реализованы правила валидации для паспортных данных
kaluga-astral/validations pull request #60
Opened 2023-08-08 09:57 UTC by IgorBabikov

# Чеклист

- [ ] Написать тесты
- [ ] Описать jsdoc
- [ ] Обновить документацию в README.md

2023-08-09 06:17 UTC, AndTem requested changes

2023-08-09 06:17 UTC, AndTem commented on package/src/seriesPassport/seriesPassport.test.ts
> +  it('Допускается длина поля - 4 цифры. Маска серии ХХ ХХ', () => {
Маска в валидации не валидируется

2023-08-09 06:17 UTC, AndTem commented on package/src/seriesPassport/seriesPassport.test.ts
> +    'Invalid for %s: Допускается длина поля - 4 цифры. Маска серии ХХ ХХ',
здесь же не длина поля проверяется

2023-08-09 06:17 UTC, AndTem commented on package/src/seriesPassport/seriesPassport.ts
> +      if (!/^(?!00)\d{2} \d{2}$/.test(value)) {
сделай для длинны поля отдельную првоерку и отдельное сообщение

2023-08-09 06:17 UTC, AndTem commented on package/src/numberPassport/numberPassport.ts
> +      if (!/^\d{6}$/.test(value)) {
Здесь лучше две отдельные проверки сделать с отдельныйми сообщениями об ошибке: только цифры и длина поля 6

2023-08-09 06:17 UTC, AndTem commented on package/src/numberPassport/numberPassport.test.ts
> +  it.each(['000100', '1000000'])(
Нет проверка на "только цифры"

2023-08-09 06:17 UTC, AndTem commented on package/src/numberPassport/numberPassport.ts
> +      if (!/^\d{6}$/.test(value)) {
Для проверки на только цифры есть правило onlyNumber

2023-08-09 06:17 UTC, AndTem commented on package/src/codePassport/codePassport.test.ts
> +  it.each(['000-456', '001-433', '009-222', '00-456'])(
Принимаем чистые данные, без маски

2023-08-09 06:17 UTC, AndTem commented on package/src/codePassport/codePassport.ts
> +      if (!/^(?!00)([0-9]{2}[0-3])[-]{1}[0-9]{3}$/.test(value)) {
Данная регулярка - неподдерживаемое решение.
Лучше сделать под каждое требование отдельный if с js проверкой

2023-08-09 08:57 UTC, IgorBabikov commented on package/src/numberPassport/numberPassport.ts
> +      if (!/^\d{6}$/.test(value)) {
Могу вот так использовать ?

      const createPassportError = (errorInfo?: string) => {
        if (errorInfo === 'errorOnlyNumber') {
          return ctx.createError({
            message:
              params?.message || PASSPORT_NUMBER_ONLY_DIGITS_ERROR_INFO.message,
            code: PASSPORT_NUMBER_ONLY_DIGITS_ERROR_INFO.code,
          });
        }

        if (errorInfo === 'errorLength') {
          return ctx.createError({
            message:
              params?.message || PASSPORT_NUMBER_LENGTH_ERROR_INFO.message,
            code: PASSPORT_NUMBER_LENGTH_ERROR_INFO.code,
          });
        }

        return ctx.createError({
          message: params?.message || PASSPORT_NUMBER_ERROR_INFO.message,
          code: PASSPORT_NUMBER_ERROR_INFO.code,
        });
      };

и уже вызвать onlyNumber и проверить на цифры

      if (onlyNumber()(value)) {
        return createPassportError('errorOnlyNumber');
      }

2023-08-09 10:08 UTC, AndTem commented on package/src/numberPassport/numberPassport.ts
> +      if (!/^\d{6}$/.test(value)) {
Не понимаю зачем так сложно.
Просто поставил if и возвращаешь сразу в функции ошибку

2023-08-09 13:25 UTC, IgorBabikov commented on package/src/seriesPassport/seriesPassport.ts
> +      if (!/^(?!00)\d{2} \d{2}$/.test(value)) {
По правилам у нас длина поля - 4 символа, соответсвенно, если указать в тесте к примеру - '9217' то пройдет, а если '92 17' ? У меня проверка что value.length если не равна 4 символам - то вернет ошибку.  Мы же проверяем только 9217 без пробела ? потому что пробел это тоже считается как символ. Верно ли я указал данную проверку что будет возвращена ошибка если  value.length не равна 4 символам ?

2023-08-10 05:11 UTC, AndTem approved these changes

2023-08-10 11:41 UTC, perevezencev approved these changes

2023-08-10 11:45 UTC, merged