feat(UIKIT-825): Добавлена возможность передачи правила валидации в a…
kaluga-astral/validations pull request #64
Opened 2023-08-30 10:56 UTC by IlyaKhazan

…ny()

# Чеклист

- [ ] Написать тесты
- [ ] Описать jsdoc
- [ ] Обновить документацию в README.md

2023-08-30 14:28 UTC, AndTem requested changes

2023-08-30 14:28 UTC, AndTem commented on package/src/any/any.test.ts
> +    //@ts-ignore
ts-ignore быть не должно

2023-08-30 14:28 UTC, AndTem commented on package/src/any/any.test.ts
> +  it('Принимает transform() для валидации значения в input', () => {
transform тут не является целевой фичей. 
Должно быть: any позволяет делать композицию для правил

2023-08-30 14:28 UTC, AndTem commented on package/src/any/any.ts
> + * @param rules - правила, валидирующие string или unknown value
rules здесь могут валидировать любые занчения

2023-08-31 06:29 UTC, AndTem requested changes

2023-08-31 06:29 UTC, AndTem commented on package/src/any/any.test.ts
> +      transform((value) => {
здесь нет композии. Должно передаваться несколько правил. transform тоже не обязательная ведь здесь правило

2023-08-31 07:26 UTC, YrStudenikin approved these changes

2023-08-31 11:08 UTC, IlyaKhazan commented on package/src/any/any.test.ts
> +      transform((value) => {
TS ругается, если я передаю композицию правил не обернутую в string(), к примеру. Поскольку передаются value с типом 'unknown'. В итоге получается вот так: 
![image](https://github.com/kaluga-astral/validations/assets/70915273/ce36f746-c22c-4e73-8c82-1a0279e308ae)

2023-08-31 12:28 UTC, AndTem commented on package/src/any/any.test.ts
> +      transform((value) => {
ну да, логично

2023-08-31 12:52 UTC, merged