feat(UIKIT-1704): Реализованы валидации для DateRange
kaluga-astral/validations pull request #90
Opened 2024-09-06 10:43 UTC by mfrolov89

# Чеклист

- [ ] Написать тесты
- [ ] Описать jsdoc
- [ ] Обновить документацию в README.md

2024-09-06 10:53 UTC, AndTem requested changes

2024-09-06 10:53 UTC, AndTem commented on package/src/rangeDateMinMax/rangeDateMinMax.ts
> +  return `${formattedDate}.${formattedMonth}.${year}`;
Почему не это API? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat

2024-09-06 10:53 UTC, AndTem commented on package/src/rangeDateMinMax/rangeDateMinMax.ts
> +    if (!value.start && !value.end) {
Проверка еще должна быть на то, что это Date

2024-09-06 10:53 UTC, AndTem commented on package/src/rangeDateInterval/rangeDateInterval.ts
> + * Проверяет значение интревала на ограничение
Описание максимально не ясное

2024-09-06 10:53 UTC, AndTem commented on package/src/core/errors/types.ts
> +  message: string | ((...ars: any) => string);
Некорректно изменять этот типп. Он вроде как предназначен для помещения внутрь error, а там у тебя не может быть функции, там будет string

2024-09-06 10:53 UTC, AndTem commented on package/src/core/utils/declensionOfWords/declensionOfWords.ts
> +export const declensionOfWords = (words: string[]) => (n: number) => {
Добавил бы сразу в пакет utils и от туда забрал

2024-09-06 10:53 UTC, AndTem commented on package/src/rangeDate/rangeDate.ts
> +export const rangeDate = <TLastSchemaValues extends Record<string, unknown>>(
Все новые правила надо описать в README

2024-09-06 11:12 UTC, mfrolov89 commented on package/src/core/errors/types.ts
> +  message: string | ((...ars: any) => string);
Я про это и спрашивал в чате
<img width="802" alt="Снимок экрана 2024-09-06 в 14 11 47" src="https://github.com/user-attachments/assets/14330a19-bdc9-497e-b181-fcc43ee73986">

2024-09-06 13:30 UTC, mfrolov89 commented on package/src/core/utils/declensionOfWords/declensionOfWords.ts
> +export const declensionOfWords = (words: string[]) => (n: number) => {
только эту или еще *Day, *Month, *Year?

Склонения для дат кажется достаточно базовым, и его можно сразу вынести в utils. Что думаешь на этот счет?

2024-09-06 13:47 UTC, AndTem commented on package/src/core/utils/declensionOfWords/declensionOfWords.ts
> +export const declensionOfWords = (words: string[]) => (n: number) => {
Поддерживаю. Можно там наделать будет много функций для сокращения конкретных слов

2024-09-10 09:17 UTC, AndTem requested changes

2024-09-10 09:17 UTC, AndTem commented on README.md
> +Проверяет значение интревала на максимально допустимое значение
```suggestion
Проверяет значение интервала на максимально допустимое значение 
```

2024-09-10 09:17 UTC, AndTem commented on README.md
> +### rangeDateInterval
```suggestion
#### rangeDateInterval
```

2024-09-10 09:17 UTC, AndTem commented on README.md
> +### rangeDateInterval
Вложи

2024-09-10 09:17 UTC, AndTem commented on README.md
> +Проверяет значение интревала на максимально допустимое значение
Надо написать как это работает + про unit нет ни слова

2024-09-10 09:17 UTC, AndTem commented on package/src/core/utils/normalizeDate/normalizeDate.ts
> +export const normalizeDate = (value: Date) => {
Тест нужен

2024-09-10 09:17 UTC, AndTem commented on package/src/rangeDateInterval/rangeDateInterval.ts
> +    if (Number.isNaN(Number(value.start)) || Number.isNaN(Number(value.end))) {
Лучше вынести в фукцию isValidDate. Такая вроде должна быть в utils

2024-09-10 09:17 UTC, AndTem commented on package/src/rangeDateInterval/rangeDateInterval.ts
> + * Проверяет значение интревала на максимально допустимое значение
Позволяет ограничить интервал на конкретное значение. Например "Дата окончания должна быть не позднее двух недель с начала"

2024-09-10 14:16 UTC, AndTem requested changes

2024-09-10 14:16 UTC, AndTem commented on README.md
> +По умолчанию значение задается в днях, но использую опцию `unit` возможна установка значения в месяцах и годах
Кривовато с точки зрения русского языка

2024-09-10 14:16 UTC, AndTem commented on README.md
> +const validate = object(rangeDateInterval({ limit: 14, }));
```suggestion
const validate = object(rangeDateInterval({ limit: 14 }));
```

2024-09-11 07:10 UTC, mfrolov89 commented on README.md
> +По умолчанию значение задается в днях, но использую опцию `unit` возможна установка значения в месяцах и годах
По умолчанию значение интервала задаётся в днях, но с помощью опции unit можно задать значение в месяцах или годах.

??

2024-09-11 08:14 UTC, AndTem commented on README.md
> +По умолчанию значение задается в днях, но использую опцию `unit` возможна установка значения в месяцах и годах
Подходит

2024-09-11 08:18 UTC, AndTem approved these changes

2024-09-11 08:18 UTC, AndTem commented on README.md
> +    - [rangeDateInterval](#range-date-interval)
Здесь забыл вложенность сделать

2024-09-11 09:30 UTC, merged